spring:
  application:
    name: wellness-assistant
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400000