// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFkfyyPHE7Ym7FUMNF09o3WmbsoqaPusY',
    appId: '1:979760746165:web:09235d1f36e90343a478fc',
    messagingSenderId: '979760746165',
    projectId: 'digital-mental-wellness-assist',
    authDomain: 'digital-mental-wellness-assist.firebaseapp.com',
    storageBucket: 'digital-mental-wellness-assist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3PpkrtjvLhc51AMCDcU_ySS09gB1BlI',
    appId: '1:979760746165:android:af588d8384a387d9a478fc',
    messagingSenderId: '979760746165',
    projectId: 'digital-mental-wellness-assist',
    storageBucket: 'digital-mental-wellness-assist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS94sbJgAJsIoKuCNU93wTLksRW1JmBXY',
    appId: '1:979760746165:ios:e694aecd0caf9c4fa478fc',
    messagingSenderId: '979760746165',
    projectId: 'digital-mental-wellness-assist',
    storageBucket: 'digital-mental-wellness-assist.firebasestorage.app',
    iosBundleId: 'com.example.digitalMentalWellnessAssitant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS94sbJgAJsIoKuCNU93wTLksRW1JmBXY',
    appId: '1:979760746165:ios:e694aecd0caf9c4fa478fc',
    messagingSenderId: '979760746165',
    projectId: 'digital-mental-wellness-assist',
    storageBucket: 'digital-mental-wellness-assist.firebasestorage.app',
    iosBundleId: 'com.example.digitalMentalWellnessAssitant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFkfyyPHE7Ym7FUMNF09o3WmbsoqaPusY',
    appId: '1:979760746165:web:a9c361427de9c907a478fc',
    messagingSenderId: '979760746165',
    projectId: 'digital-mental-wellness-assist',
    authDomain: 'digital-mental-wellness-assist.firebaseapp.com',
    storageBucket: 'digital-mental-wellness-assist.firebasestorage.app',
  );
}
